### ISSUE TITLE
[Suggestion] Add 3rd Item Pipe Mode for enhanced Round Robin 

### ISSUE THREAD

**Issue by DStrand1** [Gregicality/GregTech#140]
Add a 3rd mode for conveyor/robot arm Item Pipe modes being another form of Round Robin, but will "remember" the last place it inserted into. For example:

If I have a PipeNet with 1 input and 64 outputs, set to round robin, and I insert 64 items exactly, it will round robin perfectly, However, if I insert only 32 items, it will only go to the first half of the outputs. My idea is to then, when set to this mode, when another 32 items (or any amount) is input, it will go to the next 32 outputs, so that this "enhanced" round robin keeps track of which inventories have already received an item until all have received one.

**Comment by brachy84** [comment]
Also:

- Make robot arms able to put items into pipes. Mainly for `Supply Exact`.
