### ISSUE TITLE
Terminal issues

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [Gregicality/GregTech#158]
### Hardware Manager App

- Cannot capture items from your hotbar to be added into the hardware slots

- Some items added to the battery manager display incorrect textures
I added a MAX battery to the battery slot in the hardware manager, and it displayed at default texture instead of displaying the MAX battery texture

![2021-09-20_17-57](https://user-images.githubusercontent.com/31759736/134096649-1f1aacab-3e04-41cc-9560-0215d1e2ba09.png)

- Cannot remove batteries from the battery mounting slot.
When I open the battery mounting slot after slotting a battery, there is no way to remove the battery to swap it with a different one.

### General

- There needs to be a clear exit method from using the AR mode camera. It took me a bit to figure out that I had to right click the terminal to shut down AR mode

- Searches in apps are not cleared
Toggling the search button when in an info app, like machine guides, does not clear the search term. In addition, backspacing the search bar to empty it all the way brings up a list of all possible pages, which would be really long when more entries are added. In addition, this list is not removeable at all, so you have to look at it all the time after backspacing your search term.

- Text renders over other text, making it hard to read
![2021-09-20_17-48](https://user-images.githubusercontent.com/31759736/134096140-e10e96d5-de73-4cbd-b4dc-5047433c47d2.png)

![2021-09-20_17-52](https://user-images.githubusercontent.com/31759736/134096304-1b323863-96f6-49cf-be2c-a5f24d9f2c08.png)

- Dark mode in the App store is not saved after shutting down and reopening the terminal

- You can exit the terminal with `e` without a confirmation prompt, whereas pressing `esc` brings up a confirmation prompt. (Personally I like the direct exit over the confirmation prompt, maybe an option to disable the confirmation prompt)

- Missing Texture for the `Multiblock Helper` App Icon

- Terminal cannot be charged from GTCE batteries in players inventory in discharge mode

- My log was spammed with this error https://pastebin.com/J8pWDPdE I am not sure what was causing it though.

### Battery Manager App

When opening the app, it will close immediately.

### Right side circle button

- Cannot open an App when the left bar with maximize, minimize, close is open after clicking on the right side button

- I would like to be able to set default options (in the terminal somewhere, not the config) for when clicking on the circle on the right side, instead of bringing up the menu every time. 
Once this default option is set, it will use that option instead of bringing up the menu when you click the button can select which option to use. For example, I always want apps to close when trying to exit from them, so I don't want to have to bring up the menu every time and click close, I would rather this option just happen. Right now I just press `e` to close the entire terminal to skip the menu.
Alternatively, since this would conflict with bringing up search menus, dark mode, and other things like that, add the ability to bind Close, minimize, and maximize to a button when in the GUI. 

- Maximize button does not seem to do anything. 
I minimized an app and then clicked on the maximize button, but nothing happened.

**Comment by Yefancy** [comment]
Thanks for review.
You said that you cant open the **battery manager** app. i wonder more details, have you mounted a battery before open it? 
I just tested it. It works for me.

In addition, you can actually remove the hardware by right-click the slot. I've added tooltip with #169 

I will fix things about terminal when I have time next time. Thank you very much for your suggestions

**Comment by ALongStringOfNumbers** [comment]
Thanks for the tooltip, it was very helpful to inform me how to remove hardware. Slight issue though, when removing the hardware, it seems to be voided rather than placed into the players inventory or dropped in world.

As for the battery manager app, I have a battery mounted, with no charge, and whenever I click on the battery manager app, it brings up the screen for a second and then immediately minimizes it. I am unsure if this is because the app needs power to run or what. 

I believe this is related to the error in the pastebin that I shared above, as that error seems related to opening apps in the terminal.

If it is expected that apps close when there is no power in the battery, maybe a screen should pop up on application close saying "Closed due to low battery state, please recharge"

**Comment by Yefancy** [comment]
> Thanks for the tooltip, it was very helpful to inform me how to remove hardware. Slight issue though, when removing the hardware, it seems to be voided rather than placed into the players inventory or dropped in world.
> 
> As for the battery manager app, I have a battery mounted, with no charge, and whenever I click on the battery manager app, it brings up the screen for a second and then immediately minimizes it. I am unsure if this is because the app needs power to run or what.
> 
> I believe this is related to the error in the pastebin that I shared above, as that error seems related to opening apps in the terminal.
> 
> If it is expected that apps close when there is no power in the battery, maybe a screen should pop up on application close saying "Closed due to low battery state, please recharge"

You're right. I've reproduced it. The reason is that the battery have no energy when open the application. i will add a pop-up dialog as yousuggested
