### ISSUE TITLE
[Suggestion] Change colors via CT

### ISSUE THREAD

**Issue by SpeeeDCraft** [Gregicality/GregTech#181]
**Is your feature request related to a problem? Please describe.**
It wouldn't be bad if users could change the color of objects, as well as liquids (for example: ingots, rods), it would help add more flexibility, I think so.
This problem has already been described on GitHub GTCE.

**Describe the solution you'd like**

The ability to change the color of an object or liquid using CraftTweaker.

**Additional context**
https://github.com/GregTechCE/GregTech/issues/1691

**Comment by brachy84** [comment]
`setMaterialRGB(int materialRGB)`

**Comment by SpeeeDCraft** [comment]
> While I cannot test your new scripts in game at the moment, I have a pretty good idea of why you are crashing. `FluidMaterial` does not exist in CEu. Try removing that import.
> 
> I have yet to receive a game crash due to CT and CEu. So if it persists, something more complicated may be happening behind the scenes. I'll investigate.

It doesn't work :(
![image](https://user-images.githubusercontent.com/52341158/137423944-bc2084fa-69c7-461c-bbbd-caf9aa55ca15.png)

![image](https://user-images.githubusercontent.com/52341158/137423927-02b7eaf5-5e58-452c-8750-a36b968344f7.png)

**Comment by SpeeeDCraft** [comment]
> While I cannot test your new scripts in game at the moment, I have a pretty good idea of why you are crashing. `FluidMaterial` does not exist in CEu. Try removing that import.
> 
> I have yet to receive a game crash due to CT and CEu. So if it persists, something more complicated may be happening behind the scenes. I'll investigate.

![image](https://user-images.githubusercontent.com/52341158/137425412-50578282-e6f7-41ab-8163-e6c357ac257d.png)
![image](https://user-images.githubusercontent.com/52341158/137425426-3e40e925-131f-463d-95fa-1f20375ccb73.png)
There is no more error, but the color of the liquid does not change :)

**Comment by SpeeeDCraft** [comment]
![image](https://user-images.githubusercontent.com/52341158/137427409-4023a8ff-c523-40ee-89e3-2c28aa6c8d51.png)
It doesn't work, but now there is no error in the console. The color just doesn't change.

**Comment by SpeeeDCraft** [comment]
THIS WORKS
![image](https://user-images.githubusercontent.com/52341158/137428459-33da6fe0-52c6-4a52-94dd-4320a9e809a8.png)
Thanks!
